<a href="https://colab.research.google.com/github/ShoaibSajid/Python_CNN/blob/main/CNN_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
%cd ~
![ ! -d "./Python_CNN" ] && echo "Github Repo DOES NOT exists."
![ ! -d "./Python_CNN" ] && git clone https://github.com/ShoaibSajid/Python_CNN
![ -d "./Python_CNN" ] && echo "Github Repo exist."
%cd Python_CNN
%pip install tqdm matplotlib mnist==0.2.2 numpy
!echo 
!echo List of files
!ls

/home/gpuadmin
Github Repo exist.
/home/gpuadmin/Python_CNN
Note: you may need to restart the kernel to use updated packages.

List of files
extras	LICENSE      README.md	Yolo_Python.ipynb
layers	__pycache__  weights	Yolo_Torch.ipynb


In [2]:
# Importing libraries

from logging import raiseExceptions
import os
import pickle
from tqdm import tqdm
import mnist
import numpy as np
from layers.conv import Conv3x3, Conv3x3_n_to_n_padding, Conv3x3_1_to_n_padding
from layers.maxpool import MaxPool2
from layers.softmax import Softmax
from layers.relu import Relu
from layers.softmax_test import Softmax_test
from layers.fc import FC
from pathlib import Path
Path('weights/best').mkdir( parents=True, exist_ok=True )

In [3]:
# Define settings for run

debug=True

shuffle_data=False

run_train=True
run_val=True

load_saved_weights=False
weight_file='weights/best/best_99.pkl'

total_epoch=100
training_acc_internal=1000

In [4]:
# Initialize the network layers

conv0   = Conv3x3_1_to_n_padding( output=8                        )     # 28x28x1   -> 28x28x8  (Convolution with 8 filters)
pool0   = MaxPool2              (                                 )     # 28x28x8   -> 14x14x8  (MaxPooling 2x2)
conv1   = Conv3x3_n_to_n_padding( output=16     ,   input=8       )     # 14x14x8   -> 14x14x16 (Convolution with 8 filters)
pool1   = MaxPool2              (                                 )     # 14x14x16  -> 07x07x16 (MaxPooling 2x2)
# conv2   = Conv3x3_n_to_n_padding( output=32     ,   input=16      )
# conv3   = Conv3x3_n_to_n_padding( output=64     ,   input=32      )
fc0     = FC                    ( 7 * 7 * 16  ,   7 * 7 * 16      )     # 784       -> 784      (FC)
fc1     = FC                    ( 7 * 7 * 16  ,   10              )     # 784       -> 10       (FC)
softmax = Softmax               (                                 )     # 14x14x8   -> 10       (Softmax)
relu    = Relu                  (                                 )     # 14x14x8   -> 10       (Softmax)

In [5]:
# Defining the network - Forward propagation
def forward(im, label, debug=False):
  im        = (im / 255) - 0.5  
    
  # Conv 0 with Pool
  out_conv0 = conv0.forward   ( im            )
  out_pool0 = pool0.forward   ( out_conv0     )
  
  # Conv 1 with Pool
  out_conv1 = conv1.forward   ( out_pool0     )
  out_pool1 = pool1.forward   ( out_conv1     )
  
  # Swap axes to realign for flattening
  out_pool2 = np.swapaxes(out_pool1,0,2)
  out_pool3 = np.swapaxes(out_pool2,1,2)
  
  # FC0 and Relu
  out_fc0   = fc0.forward     ( out_pool3     )
  
  # FC1 and SoftMax
  out_fc1   = fc1.forward     ( out_fc0       )
  out_soft  = softmax.forward ( out_fc1       )
  
  if debug:
    print(f"Input Image: {im[-4]}\n")
    print(f"x_conv0 filters : {conv0.filters[0]}\n")
    print(f"x_conv0 : {out_conv0[:,:,0][-1]}\n")
    print(f"MaxPool0: {out_pool0[:,:,0][-1]}\n")
    print(f"x_conv1 filters : {conv1.filters[0,:,:,0]}\n")
    print(f"x_conv1 : {out_conv1[:,:,0][-1]}\n")
    print(f"MaxPool1: {out_pool1[:,:,0][-1]}\n")
    print(f"FC0 Weights: {fc0.weights[:,0][:10]}\n")
    print(f"FC0 output: {out_fc0[:10]}\n")
    print(f"FC1 Weights: {fc1.weights[:,0][:10]}\n")
    print(f"FC1 output: {out_fc1[:10]}\n")
    print(f"SoftMax output: {out_soft}\n")

  return out_soft

In [6]:
# Defining the network - Backward propagation
def backward(label, out, loss=1, lr=0.005):
  # Calculate initial gradient
  gradient = np.zeros(10)
  gradient[label] = -1 / out[label]
  # gradient[label] = -loss / out[label]

  # ------------------------------Backprop-----------------------------------
  # SoftMax
  gradient_softmax = softmax.backprop ( gradient                              )     

  # FC1 and FC0 
  gradient_fc1 = fc1.backprop         ( gradient_softmax  ,               lr  )
  gradient_fc0 = fc0.backprop         ( gradient_fc1      ,               lr  )

  # Swap axes to realign for flattening
  gradient_swap0 = np.swapaxes        ( gradient_fc0      ,       1   ,   2   )
  gradient_swap1 = np.swapaxes        ( gradient_swap0    ,       0   ,   2   )

  # Conv 1 with Pool 
  gradient_pool1 = pool1.backprop     ( gradient_swap1                        )
  gradient_conv1 = conv1.backprop     ( gradient_pool1     ,              lr  )

  # Conv 0 with Pool 
  gradient_pool0 = pool0.backprop     ( gradient_conv1                        ) 
  gradient_conv0 = conv0.backprop     ( gradient_pool0     ,              lr  )
  return None

In [7]:
# Defining the network - Loss Function (Cross Entropy)
# Calculate cross-entropy loss and accuracy. np.log() is the natural log.
def cal_loss(out_soft, label):
  loss = -np.log(out_soft[label])
  acc = 1 if np.argmax(out_soft) == label else 0
  return out_soft, loss, acc

In [8]:
# Defining the network - Training Function
def train(im, label, debug=False, lr=.005):
  pred = forward(im, label, debug)
  out_soft, loss, acc = cal_loss(pred, label)
  backward(label, out_soft, loss=loss, lr=0.005)
  return loss, acc

In [9]:
# Defining the network - Validation Function
def val(im, label):
  pred = forward(im, label)
  out_soft, loss, acc = cal_loss(pred, label)
  return loss, acc

In [10]:
# Function definitions to save and load weight files

def save_weights(name,lr=0,max_acc=0):
  print(f"\nSaving new weights ({name}).")
  weights = dict()
  weights["conv0"]        = conv0.filters
  weights["conv1"]        = conv1.filters
  weights["fc0_weights"]  = fc0.weights
  weights["fc0_biases" ]  = fc0.biases
  weights["fc1_weights"]  = fc1.weights
  weights["fc1_biases" ]  = fc1.biases
  weights["lr" ]          = lr
  weights["max_acc"]      = max_acc
  weight_file = open(str(name), "wb")
  pickle.dump(weights, weight_file)
  weight_file.close()
  
def load_weights(name):
  if os.path.isfile(name): 
    weight_file = open(str(name), "rb")
    weights = pickle.load(weight_file)
    conv0.filters  = weights["conv0"]      
    conv1.filters  = weights["conv1"]      
    fc0.weights    = weights["fc0_weights"]
    fc0.biases     = weights["fc0_biases" ]
    fc1.weights    = weights["fc1_weights"]
    fc1.biases     = weights["fc1_biases" ]
    lr             = weights["lr" ]
    max_acc        = weights["max_acc"]
    print(f"\nLoading weights from {name} file. LR restored to {lr}. Last Accuracy {max_acc}%")
    return lr, max_acc
  else:
    print("Weights file not found.")
    lr=0.005
    max_acc=0
    return lr, max_acc
   

In [11]:
# Defining the network - Adjust learning rate
def adjust_lr(acc, lr=.005):
  if   acc > 98: lr=0.00001
  elif acc > 95: lr=0.0005
  elif acc > 90: lr=0.001
  elif acc > 80: lr=0.002
  elif acc > 70: lr=0.003
  elif acc > 60: lr=0.004
  return lr

In [12]:
# Load Weights
if load_saved_weights:
    lr, max_acc = load_weights(weight_file)
else:
    lr, max_acc = 0.005, 0 

if debug: save_weights(f'weights/debug.pkl', lr, max_acc)


Saving new weights (weights/debug.pkl).


In [13]:
# Importing the training dataset - MNIST Dataset

train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

In [14]:
# Shuffle Data
permutation = np.random.permutation(len(train_images))
train_images = train_images[permutation]
train_labels = train_labels[permutation]

In [15]:
 # Main function to run the training

if run_train:
  print(f'Training Initialized.')
  print(f"\tTotal number of training   images: {len(train_labels)}")
  print(f"\tTotal number of validation images: {len(test_labels)}")
  print(f"\tTraining will run for {total_epoch} epochs.")
  print(f"\tResults will be logged after every {training_acc_internal} images.")
  for epoch in range(total_epoch):
    print('\n--- Epoch %d ---' % (epoch + 1))
            
    # Initialize Variables
    loss, num_correct = 0, 0
    for i, (im, label) in tqdm(enumerate(zip(train_images, train_labels))):
      
      # Logging results
      if i % training_acc_internal == training_acc_internal-1:
        lr = adjust_lr(num_correct)
        print(f'\n[Step {(i+1)}] : For {training_acc_internal} iterations, the Avg Loss is {np.round((loss / training_acc_internal),2)} | Training Acc: {num_correct/training_acc_internal} | LR: {lr}')
        loss, num_correct = 0, 0
          
      # Train the network
      l, acc = train(im, label, debug, lr=lr)
      loss += l
      num_correct += acc
           
    print(f"End of epoch {epoch+1}")      

    print(f"\n\nCalculating validation scores at the end of epoch.")
    loss, num_correct = 0, 0
    for im, label in tqdm(zip(test_images, test_labels)):
      l, acc = val(im, label)
      loss += l
      num_correct += acc
    num_tests = len(test_images)
    test_loss, test_acc =  loss / num_tests , num_correct / num_tests
    print('Test Loss:', test_loss)
    print('Test Accuracy:', test_acc)

    if epoch == 0:
      max_acc = test_acc
    elif test_acc > max_acc: 
      max_acc = test_acc
      save_weights(f'weights/best/best_{test_acc}.pkl', lr, max_acc)
      save_weights(f'weights/last.pkl', lr, max_acc)


Training Initialized.
	Total number of training   images: 60000
	Total number of validation images: 10000
	Training will run for 100 epochs.
	Results will be logged after every 1000 images.

--- Epoch 1 ---


1it [00:00,  7.58it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.01764706  0.49215686  0.48823529  0.48823529  0.40196078
 -0.40588235 -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08345868  0.15709042  0.09174283]
 [-0.17737623  0.02582812  0.19399587]
 [ 0.00353801  0.02167659  0.08305948]]

x_conv0 : [-0.23432862 -0.10391116 -0.10391116 -0.10391116 -0.10391116 -0.10391116
 -0.10391116 -0.10391116 -0.10391116 -0.10391116 -0.10391116 -0.10391116
 -0.10391116 -0.10391116 -0.10391116 -0.10391116 -0.10391116 -0.10391116
 -0.10391116 -0.10391116 -0.10391116 -0.10391116 -0.10391116 -0.10391116
 -0.10391116 -0.10391116 -0.10391116  0.03895819]

MaxPool0: [-0.10391116 -0.10391116 -0.10391116 -0.10391116 -0.10391116 -0.10391116
 -0.10391116 -0.02526277 -0.10391116 -0.10391116 -0.10391116 -0.10391116
 -0.10391116  0.038

3it [00:00,  8.48it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.44117647  0.35882353  0.48823529  0.26078431
 -0.46470588 -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08347931  0.1570695   0.09172487]
 [-0.1773979   0.02580663  0.19397792]
 [ 0.00351694  0.02165486  0.08304088]]

x_conv0 : [-0.23428946 -0.10385085 -0.10385085 -0.10385085 -0.10385085 -0.10385085
 -0.10385085 -0.10385085 -0.10385085 -0.10385085 -0.10385085 -0.10385085
 -0.10385085 -0.10385085 -0.10385085 -0.10385085 -0.10385085 -0.10385085
 -0.10385085 -0.10385085 -0.10385085 -0.10385085 -0.10385085 -0.10385085
 -0.10385085 -0.10385085 -0.10385085  0.03900055]

MaxPool0: [-0.10385085 -0.10385085 -0.10385085 -0.10385085 -0.10385085 -0.10385085
 -0.10385085 -0.09943817 -0.02200764 -0.10385085 -0.10385085 -0.10385085
 -0.10385085  0.039

5it [00:00,  8.40it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.46078431  0.1745098
  0.49215686  0.17058824 -0.14313725 -0.38235294 -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08347198  0.15707835  0.09172972]
 [-0.17738318  0.02582321  0.19398974]
 [ 0.0035341   0.0216744   0.08305647]]

x_conv0 : [-0.23431051 -0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292
 -0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292
 -0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292
 -0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292
 -0.10388292 -0.10388292 -0.10388292  0.0389768 ]

MaxPool0: [-0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292
 -0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292 -0.10388292
 -0.10388292  0.0389

7it [00:00,  8.64it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08346674  0.15708373  0.09173535]
 [-0.17738052  0.02582471  0.19399183]
 [ 0.00353435  0.02167416  0.08305678]]

x_conv0 : [-0.23431781 -0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418
 -0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418
 -0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418
 -0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418
 -0.10389418 -0.10389418 -0.10389418  0.03896941]

MaxPool0: [-0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418
 -0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418 -0.10389418
 -0.10389418  0.03896941]

x_conv1 filters : [[ 0.0096305  -0.10965753  0.23074704]
 [-0.04479849  0.04082681 -0.24593627]
 [-0.04717722  0.06643063  0.21413338]]

x_conv1 : [-0.22729145 -0.3078851

9it [00:01,  8.20it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08347372  0.15707565  0.09172519]
 [-0.17738703  0.02581618  0.19398162]
 [ 0.00352535  0.02166369  0.0830455 ]]

x_conv0 : [-0.23429932 -0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894
 -0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894
 -0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894
 -0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894
 -0.10386894 -0.10386894 -0.10386894  0.03898446]

MaxPool0: [-0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894
 -0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894 -0.10386894
 -0.10386894  0.03898446]

x_conv1 filters : [[ 0.00963118 -0.10965747  0.23074692]
 [-0.04479757  0.04082714 -0.2459366 ]
 [-0.04717628  0.06643118  0.21413345]]

x_conv1 : [-0.22726187 -0.3078451

11it [00:01,  7.57it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.4372549
  0.38627451  0.48823529  0.48823529 -0.11176471 -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08348665  0.1570634   0.09171592]
 [-0.17740014  0.02580349  0.19397114]
 [ 0.00351627  0.02165486  0.08303812]]

x_conv0 : [-0.23427698 -0.10383358 -0.10383358 -0.10383358 -0.10383358 -0.10383358
 -0.10383358 -0.10383358 -0.10383358 -0.10383358 -0.10383358 -0.10383358
 -0.10383358 -0.10383358 -0.10383358 -0.10383358 -0.10383358 -0.10383358
 -0.10383358 -0.10383358 -0.10383358 -0.10383358 -0.10383358 -0.10383358
 -0.10383358 -0.10383358 -0.10383358  0.03900995]

MaxPool0: [-0.10383358 -0.10383358 -0.10383358 -0.10383358 -0.10383358 -0.10383358
 -0.10383358 -0.10383358 -0.10383358 -0.0096184  -0.10383358 -0.10383358
 -0.10383358  0.0390

13it [00:01,  8.21it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08346265  0.15708728  0.0917379 ]
 [-0.17737479  0.02582951  0.19399516]
 [ 0.00354163  0.02168116  0.08306244]]

x_conv0 : [-0.23432492 -0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621
 -0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621
 -0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621
 -0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621
 -0.10390621 -0.10390621 -0.10390621  0.03896032]

MaxPool0: [-0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621
 -0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621 -0.10390621
 -0.10390621  0.03896032]

x_conv1 filters : [[ 0.00963226 -0.10965589  0.23074803]
 [-0.04479633  0.04082875 -0.24593571]
 [-0.04717498  0.06643269  0.21413416]]

x_conv1 : [-0.22738258 -0.3080615

15it [00:01,  7.57it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08345465  0.1570977   0.09174919]
 [-0.17736186  0.02584358  0.19400921]
 [ 0.00355414  0.02169423  0.08307563]]

x_conv0 : [-0.23434984 -0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159
 -0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159
 -0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159
 -0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159
 -0.10394159 -0.10394159 -0.10394159  0.03893761]

MaxPool0: [-0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159
 -0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159 -0.10394159
 -0.10394159  0.03893761]

x_conv1 filters : [[ 0.0096325  -0.10965628  0.23074778]
 [-0.04479582  0.04082855 -0.24593578]
 [-0.04717428  0.06643256  0.21413478]]

x_conv1 : [-0.22741755 -0.3080663

17it [00:02,  7.47it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.16666667  0.48823529  0.48823529
 -0.33529412 -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08343836  0.1571143   0.09176496]
 [-0.17734199  0.02586362  0.1940264 ]
 [ 0.00357568  0.02171617  0.08309385]]

x_conv0 : [-0.23438464 -0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447
 -0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447
 -0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447
 -0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447
 -0.10399447 -0.10399447 -0.10399447  0.03890121]

MaxPool0: [-0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447
 -0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447 -0.10399447
 -0.10399447  0.038

19it [00:02,  7.35it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.06078431  0.48823529  0.41372549 -0.30392157
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08347496  0.15707695  0.09172929]
 [-0.17738273  0.02582308  0.1939882 ]
 [ 0.00353799  0.02167829  0.08305798]]

x_conv0 : [-0.23430876 -0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991
 -0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991
 -0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991
 -0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991
 -0.10387991 -0.10387991 -0.10387991  0.03897883]

MaxPool0: [-0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991
 -0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991 -0.10387991
 -0.10387991  0.038

21it [00:02,  7.08it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.1         0.49215686  0.48823529 -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08347182  0.15707698  0.09172821]
 [-0.17738539  0.02581749  0.19398144]
 [ 0.00353412  0.02167226  0.08305169]]

x_conv0 : [-0.23430206 -0.10387346 -0.10387346 -0.10387346 -0.10387346 -0.10387346
 -0.10387346 -0.10387346 -0.10387346 -0.10387346 -0.10387346 -0.10387346
 -0.06718217  0.03557737  0.00473485 -0.15511733 -0.11369367 -0.10387346
 -0.10387346 -0.10387346 -0.10387346 -0.10387346 -0.10387346 -0.10387346
 -0.10387346 -0.10387346 -0.10387346  0.03898137]

MaxPool0: [-0.10387346 -0.10387346 -0.10387346 -0.10387346 -0.10387346 -0.10387346
  0.16953105  0.02260521 -0.10387346 -0.10387346 -0.10387346 -0.10387346
 -0.10387346  0.03898137]


23it [00:02,  7.25it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5         0.47647059
  0.49215686  0.49215686  0.39411765 -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08345159  0.1571      0.09175176]
 [-0.17736112  0.02584383  0.19400817]
 [ 0.00355688  0.02169668  0.08307716]]

x_conv0 : [-0.23435188 -0.10394552 -0.10394552 -0.10394552 -0.10394552 -0.10394552
 -0.10394552 -0.10394552 -0.10394552 -0.10394552 -0.10394552 -0.10394552
 -0.10394552 -0.10394552 -0.10394552 -0.10394552 -0.10394552 -0.10394552
 -0.10394552 -0.10394552 -0.10394552 -0.10394552 -0.10394552 -0.10394552
 -0.10394552 -0.10394552 -0.10394552  0.03893444]

MaxPool0: [-0.10394552 -0.10394552  0.05244047  0.02530044 -0.10394552 -0.10394552
 -0.10394552 -0.10394552 -0.10394552 -0.10394552 -0.10394552 -0.10394552
 -0.10394552  0.038

26it [00:03,  7.97it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5         0.22156863  0.49607843
 -0.02941176 -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08344243  0.15710848  0.09176176]
 [-0.17735169  0.02585341  0.19402079]
 [ 0.00356435  0.02170448  0.08308737]]

x_conv0 : [-0.23437222 -0.10397517 -0.10397517 -0.10397517 -0.10397517 -0.10397517
 -0.10397517 -0.10397517 -0.10397517 -0.10397517 -0.10397517 -0.10397517
 -0.10397517 -0.10397517 -0.10397517 -0.10397517 -0.10397517 -0.10397517
 -0.10397517 -0.10397517 -0.10397517 -0.10397517 -0.10397517 -0.10397517
 -0.10397517 -0.10397517 -0.10397517  0.03891611]

MaxPool0: [-0.10397517 -0.10397517 -0.10397517 -0.10397517 -0.10397517 -0.10397517
 -0.10397517 -0.10397517  0.01172041 -0.10397517 -0.10397517 -0.10397517
 -0.10397517  0.038

28it [00:03,  8.35it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.47254902  0.24901961  0.49607843 -0.26470588 -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08345107  0.15709987  0.09175237]
 [-0.17736173  0.02584286  0.19401054]
 [ 0.00355558  0.02169549  0.08307805]]

x_conv0 : [-0.23435282 -0.10394642 -0.10394642 -0.10394642 -0.10394642 -0.10394642
 -0.10394642 -0.10394642 -0.10394642 -0.10394642 -0.10394642 -0.08883426
  0.01332141  0.08089064 -0.11498912 -0.14223573 -0.10394642 -0.10394642
 -0.10394642 -0.10394642 -0.10394642 -0.10394642 -0.10394642 -0.10394642
 -0.10394642 -0.10394642 -0.10394642  0.03893504]

MaxPool0: [-0.10394642 -0.10394642 -0.10394642 -0.10394642 -0.10394642 -0.08883426
  0.15666304 -0.11498912 -0.10394642 -0.10394642 -0.10394642 -0.10394642
 -0.10394642  0.03893504]


29it [00:03,  8.45it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08345658  0.15709619  0.09174665]
 [-0.17736661  0.02584     0.19400542]
 [ 0.0035522   0.02169251  0.08307262]]

x_conv0 : [-0.23434413 -0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254
 -0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254
 -0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254
 -0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254
 -0.10393254 -0.10393254 -0.10393254  0.0389435 ]

MaxPool0: [-0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254
 -0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254 -0.10393254
 -0.10393254  0.0389435 ]

x_conv1 filters : [[ 0.00963482 -0.10965481  0.23074908]
 [-0.04479318  0.04083038 -0.24593384]
 [-0.04717154  0.06643431  0.21413716]]

x_conv1 : [-0.22748376 -0.3083494

32it [00:04,  8.62it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5         0.23333333  0.49215686  0.49215686  0.49215686
  0.49215686  0.38627451 -0.44117647 -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08346977  0.15708395  0.09173676]
 [-0.17738181  0.02582518  0.19399255]
 [ 0.00353758  0.02167744  0.0830604 ]]

x_conv0 : [-0.23431922 -0.10389343 -0.10389343 -0.10389343 -0.10389343 -0.10389343
 -0.10389343 -0.10389343 -0.10389343 -0.10389343 -0.10389343 -0.10389343
 -0.10389343 -0.10389343 -0.10389343 -0.10389343 -0.10389343 -0.10389343
 -0.10389343 -0.10389343 -0.10389343 -0.10389343 -0.10389343 -0.10389343
 -0.10389343 -0.10389343 -0.10389343  0.03897123]

MaxPool0: [-0.10389343 -0.10389343 -0.10389343 -0.10389343 -0.10389343 -0.10389343
 -0.10389343 -0.02499223 -0.00930719 -0.10389343 -0.10389343 -0.10389343
 -0.10389343  0.038

34it [00:04,  8.69it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.48431373 -0.14313725
  0.35490196  0.5         0.5         0.5         0.34313725 -0.39803922
 -0.48431373 -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08346057  0.15709541  0.0917487 ]
 [-0.17736939  0.0258389   0.19400654]
 [ 0.00354934  0.02168999  0.08307307]]

x_conv0 : [-0.23434478 -0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979
 -0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979
 -0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979
 -0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979
 -0.10392979 -0.10392979 -0.10392979  0.03894782]

MaxPool0: [-0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979
 -0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979 -0.10392979
 -0.10392979

35it [00:04,  8.72it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.40980392
  0.39803922  0.49607843  0.49607843  0.46078431  0.27254902 -0.45294118
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.0834741   0.15708128  0.09173668]
 [-0.17738169  0.02582611  0.19399555]
 [ 0.00353617  0.02167754  0.08306158]]

x_conv0 : [-0.23431981 -0.10389192 -0.10389192 -0.10389192 -0.10389192 -0.10389192
 -0.10389192 -0.10389192 -0.10389192 -0.10389192 -0.10389192 -0.10389192
 -0.10389192 -0.10389192 -0.10389192 -0.10389192 -0.10389192 -0.10389192
 -0.10389192 -0.10389192 -0.10389192 -0.10389192 -0.10389192 -0.10389192
 -0.10389192 -0.10389192 -0.10389192  0.0389742 ]

MaxPool0: [-0.10389192 -0.10389192 -0.10389192 -0.10389192 -0.10389192 -0.09651203
  0.03868422 -0.07949185 -0.10389192 -0.10389192 -0.10389192 -0.10389192
 -0.10389192

38it [00:04,  8.57it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5         0.22156863  0.49607843  0.29215686 -0.19019608
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08350247  0.15705337  0.09171216]
 [-0.17741117  0.02579671  0.19396918]
 [ 0.00350807  0.02164859  0.08303563]]

x_conv0 : [-0.23426571 -0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889
 -0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889
 -0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889
 -0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889
 -0.10380889 -0.10380889 -0.10380889  0.03903178]

MaxPool0: [-0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889
 -0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889 -0.10380889
 -0.10380889  0.039

39it [00:04,  8.53it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.47254902  0.23333333  0.48823529
  0.48823529 -0.20196078 -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08350621  0.15705085  0.09171116]
 [-0.17741373  0.02579629  0.19397009]
 [ 0.00350689  0.02164739  0.0830358 ]]

x_conv0 : [-0.23426419 -0.10380422 -0.10380422 -0.10380422 -0.10380422 -0.10380422
 -0.10380422 -0.10380422 -0.10380422 -0.10380422 -0.10380422 -0.10380422
 -0.10380422 -0.10380422 -0.10380422 -0.10380422 -0.10380422 -0.10380422
 -0.10380422 -0.10380422 -0.10380422 -0.10380422 -0.10380422 -0.10380422
 -0.10380422 -0.10380422 -0.10380422  0.0390364 ]

MaxPool0: [-0.10380422 -0.10380422 -0.10380422 -0.10380422 -0.10380422  0.0113926
 -0.10380422 -0.10380422 -0.10380422 -0.10380422 -0.10380422 -0.10380422
 -0.10380422  0.0390

41it [00:05,  8.53it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.3745098   0.39411765
  0.09215686 -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08353654  0.15702042  0.0916812 ]
 [-0.17744705  0.02576264  0.19393693]
 [ 0.00347162  0.0216117   0.08300176]]

x_conv0 : [-0.23420059 -0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088
 -0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088
 -0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088
 -0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088
 -0.1037088  -0.1037088  -0.1037088   0.03910027]

MaxPool0: [-0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088
 -0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088  -0.1037088
 -0.1037088   0.03910027]

43it [00:05,  7.49it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.47647059 -0.06862745  0.49215686  0.46078431 -0.01372549 -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08355051  0.15700615  0.0916647 ]
 [-0.17746251  0.0257464   0.19391892]
 [ 0.00345446  0.02159529  0.08298253]]

x_conv0 : [-0.23416809 -0.10366158 -0.10366158 -0.10366158 -0.10366158 -0.07454456
  0.03679726  0.04724497 -0.14805509 -0.12397582 -0.10366158 -0.10366158
 -0.10366158 -0.10366158 -0.10366158 -0.10366158 -0.10366158 -0.10366158
 -0.10366158 -0.10366158 -0.10366158 -0.10366158 -0.10366158 -0.10366158
 -0.10366158 -0.10366158 -0.10366158  0.03913023]

MaxPool0: [-0.10366158 -0.10366158 -0.06336823  0.18875401 -0.12397582 -0.10366158
 -0.10366158 -0.10366158 -0.10366158 -0.10366158 -0.10366158 -0.10366158
 -0.10366158  0.03913023]


45it [00:05,  7.79it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.26078431  0.49215686  0.34705882 -0.35882353 -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08354622  0.15701079  0.0916683 ]
 [-0.17745405  0.02575428  0.19392511]
 [ 0.00346331  0.02160342  0.08298901]]

x_conv0 : [-0.23417924 -0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911
 -0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911
 -0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911
 -0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911
 -0.10367911 -0.10367911 -0.10367911  0.0391176 ]

MaxPool0: [-0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911
 -0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911 -0.10367911
 -0.10367911  0.0391176 ]


47it [00:05,  8.19it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5         0.39019608  0.48823529 -0.0372549  -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08356124  0.15699521  0.09165314]
 [-0.1774727   0.02573497  0.19390573]
 [ 0.00344606  0.02158563  0.08297138]]

x_conv0 : [-0.23414453 -0.10362756 -0.10362756 -0.10362756 -0.10362756 -0.10362756
 -0.10362756 -0.10362756 -0.10362756 -0.10362756 -0.10362756 -0.10362756
 -0.10362756 -0.10362756 -0.10362756 -0.10362756 -0.10362756 -0.10362756
 -0.10362756 -0.10362756 -0.10362756 -0.10362756 -0.10362756 -0.10362756
 -0.10362756 -0.10362756 -0.10362756  0.03915188]

MaxPool0: [-0.10362756 -0.10362756 -0.10362756 -0.10362756 -0.10362756 -0.10362756
 -0.10362756 -0.10362756 -0.10362756  0.02406457  0.0320478  -0.10362756
 -0.10362756  0.03915188]


49it [00:06,  8.48it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.24901961  0.24901961  0.24901961 -0.24901961
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08354989  0.15700694  0.09166292]
 [-0.17745937  0.02574916  0.19391835]
 [ 0.00346035  0.02160067  0.08298496]]

x_conv0 : [-0.23416868 -0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405
 -0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405
 -0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405
 -0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405
 -0.10366405 -0.10366405 -0.10366405  0.03912658]

MaxPool0: [-0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405
 -0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405 -0.10366405
 -0.10366405  0.039

52it [00:06,  8.64it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5         0.44117647  0.49607843 -0.39803922 -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08357028  0.15698634  0.09164466]
 [-0.17748183  0.02572619  0.1938975 ]
 [ 0.00343954  0.02157937  0.08296673]]

x_conv0 : [-0.23412735 -0.10360129 -0.10360129 -0.10360129 -0.10360129 -0.10360129
 -0.10360129 -0.10360129 -0.10360129 -0.10360129 -0.10360129 -0.10360129
 -0.10360129 -0.09569469 -0.01386652  0.07109575 -0.08504385 -0.15046619
 -0.10360129 -0.10360129 -0.10360129 -0.10360129 -0.10360129 -0.10360129
 -0.10360129 -0.10360129 -0.10360129  0.03916979]

MaxPool0: [-0.10360129 -0.10360129 -0.10360129 -0.10360129 -0.10360129 -0.10360129
 -0.09569469  0.17406582 -0.08504385 -0.10360129 -0.10360129 -0.10360129
 -0.10360129  0.03916979]


54it [00:06,  8.68it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.10784314  0.14705882 -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08355544  0.15700053  0.0916581 ]
 [-0.17746656  0.02574023  0.19391069]
 [ 0.00345264  0.02159083  0.08297768]]

x_conv0 : [-0.23415478 -0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378
 -0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378
 -0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378
 -0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378
 -0.10364378 -0.10364378 -0.10364378  0.03914062]

MaxPool0: [-0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378
 -0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378 -0.10364378
 -0.10364378  0.03914062]


55it [00:06,  8.67it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08357537  0.1569822   0.09164241]
 [-0.17748745  0.0257199   0.19389324]
 [ 0.00343131  0.02156944  0.08295904]]

x_conv0 : [-0.23411888 -0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747
 -0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747
 -0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747
 -0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747
 -0.10358747 -0.10358747 -0.10358747  0.03918036]

MaxPool0: [-0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747
 -0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747 -0.10358747
 -0.10358747  0.03918036]

x_conv1 filters : [[ 0.00964137 -0.10964816  0.23075332]
 [-0.04478517  0.04083694 -0.24593083]
 [-0.04716471  0.06644057  0.2141405 ]]

x_conv1 : [-0.22774796 -0.3093557

57it [00:07,  8.53it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08358023  0.15697608  0.0916355 ]
 [-0.17749424  0.02571171  0.19388376]
 [ 0.00342701  0.02156467  0.08295295]]

x_conv0 : [-0.23410352 -0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629
 -0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629
 -0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629
 -0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629
 -0.10356629 -0.10356629 -0.10356629  0.03919334]

MaxPool0: [-0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629
 -0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629 -0.10356629
 -0.10356629  0.03919334]

x_conv1 filters : [[ 0.00964234 -0.10964705  0.2307541 ]
 [-0.04478393  0.04083798 -0.24593007]
 [-0.04716355  0.06644155  0.2141412 ]]

x_conv1 : [-0.22788069 -0.3095959

60it [00:07,  8.71it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08357674  0.15698259  0.09164256]
 [-0.17748485  0.02572315  0.19389369]
 [ 0.00343545  0.02157364  0.08296035]]

x_conv0 : [-0.234121   -0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902
 -0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902
 -0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902
 -0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902
 -0.1035902  -0.1035902  -0.1035902   0.03917792]

MaxPool0: [-0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902
 -0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902  -0.1035902
 -0.1035902   0.03917792]

x_conv1 filters : [[ 0.00964246 -0.10964677  0.23075442]
 [-0.04478362  0.04083834 -0.24592959]
 [-0.04716329  0.06644195  0.21414187]]

x_conv1 : [-0.22803401 -0.30973887 -0.3

61it [00:07,  8.69it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08359192  0.15696804  0.09163017]
 [-0.17750235  0.02570667  0.19387929]
 [ 0.00342008  0.02155895  0.0829491 ]]

x_conv0 : [-0.23409208 -0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495
 -0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495
 -0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495
 -0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495
 -0.10354495 -0.10354495 -0.10354495  0.03920978]

MaxPool0: [-0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495
 -0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495 -0.10354495
 -0.10354495  0.03920978]

x_conv1 filters : [[ 0.00964324 -0.10964574  0.23075537]
 [-0.04478277  0.04083933 -0.24592869]
 [-0.04716264  0.0664429   0.21414278]]

x_conv1 : [-0.22814047 -0.3099387

64it [00:07,  8.68it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.13137255 -0.11176471
 -0.11176471 -0.46470588 -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08358312  0.15697619  0.09163942]
 [-0.17749294  0.02571442  0.1938875 ]
 [ 0.00342658  0.02156475  0.08295729]]

x_conv0 : [-0.23410877 -0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074
 -0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074
 -0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074
 -0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074
 -0.10357074 -0.10357074 -0.10357074  0.03919272]

MaxPool0: [-0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074
 -0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074 -0.10357074
 -0.10357074  0.039

65it [00:07,  8.65it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08357127  0.15699065  0.09165421]
 [-0.17747545  0.02573481  0.19390788]
 [ 0.00344841  0.02158776  0.08297991]]

x_conv0 : [-0.23414378 -0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042
 -0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042
 -0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042
 -0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042
 -0.10362042 -0.10362042 -0.10362042  0.03916063]

MaxPool0: [-0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042
 -0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042 -0.10362042
 -0.10362042  0.03916063]

x_conv1 filters : [[ 0.00964319 -0.109646    0.23075445]
 [-0.04478355  0.04083841 -0.24593017]
 [-0.04716387  0.06644176  0.21414158]]

x_conv1 : [-0.22808899 -0.3097675

68it [00:08,  8.57it/s]

Input Image: [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]

x_conv0 filters : [[-0.08356626  0.15699506  0.09165576]
 [-0.17746876  0.02574143  0.19391139]
 [ 0.00345449  0.02159435  0.08298486]]

x_conv0 : [-0.23415182 -0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431
 -0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431
 -0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431
 -0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431
 -0.10363431 -0.10363431 -0.10363431  0.03914927]

MaxPool0: [-0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431
 -0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431 -0.10363431
 -0.10363431  0.03914927]

x_conv1 filters : [[ 0.00964306 -0.10964568  0.23075427]
 [-0.04478414  0.04083856 -0.24593019]
 [-0.04716436  0.06644186  0.21414162]]

x_conv1 : [-0.22818432 -0.3098385

69it [00:08,  8.12it/s]

Input Image: [-0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5        -0.5        -0.5
 -0.5        -0.14705882  0.5         0.44509804 -0.5        -0.5
 -0.5        -0.5        -0.5        -0.5       ]

x_conv0 filters : [[-0.08357986  0.15698334  0.09164762]
 [-0.17748673  0.02572602  0.19389951]
 [ 0.00343604  0.02157847  0.08297287]]

x_conv0 : [-0.23412824 -0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495
 -0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495
 -0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495
 -0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495
 -0.10359495 -0.10359495 -0.10359495  0.03917861]

MaxPool0: [-0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495
 -0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495 -0.10359495
 -0.10359495  0.03917861]


KeyboardInterrupt: 

In [ ]:
# Main function to validate the weights

if run_val:
  print(f'\n--- Testing the CNN for {len(test_labels)} images---')
  loss = 0
  num_correct = 0
  for im, label in tqdm(zip(test_images, test_labels)):
    l, acc = val(im, label)
    loss += l 
    num_correct += acc

  num_tests = len(test_images)
  print('\nTest Loss:', loss / num_tests)
  print('Test Accuracy:', num_correct / num_tests)