In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [6]:
torch.manual_seed(42)
a = torch.rand((1, 3), requires_grad=True)
b = torch.randn((1, 3), requires_grad=True)
x = a ** 3 + b ** 2
x = x.sum()
print(a, b)
print(x)

tensor([[0.8823, 0.9150, 0.3829]], requires_grad=True) tensor([[-0.8293, -1.6137, -0.2147]], requires_grad=True)
tensor(4.8469, grad_fn=<SumBackward0>)


In [7]:
x.backward()

In [9]:
print(a.grad)

tensor([[2.3352, 2.5117, 0.4398]])


In [10]:
print(b.grad)

tensor([[-1.6586, -3.2274, -0.4294]])


In [11]:
a.grad == 3 * a ** 2

tensor([[True, True, True]])